version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FRONTEND_URL=http://localhost:5173
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001/api
      - VITE_DYNAMIC_ENVIRONMENT_ID=${DYNAMIC_ENVIRONMENT_ID}
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend
