service: web3-signature-backend

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    NODE_ENV: ${self:provider.stage}
  httpApi:
    cors:
      allowedOrigins:
        - "http://localhost:3000"
        - "http://localhost:3003"
        - "https://*.vercel.app"
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001
    host: 0.0.0.0

functions:
  # API
  - ${file(sls/functions/api/main.yml)}

package:
  exclude:
    - node_modules/**
    - .git/**
    - .vscode/**
    - "*.md"
    - "src/**"
  include:
    - "dist/**"
